### ISSUE TITLE
Making this work with a valid cert

### ISSUE THREAD

**Issue by absolutejam** [TheHipbot/docker-web2py#3]
Hey,

I've tried simply mounted my own cert directory over the top of the /etc/nginx/ssl directory (To replace the .crt and .key file) but the pages aren't accessible when doing this. Is there a quick and easy way to get up and running with a valid cert?

Thanks.

**Comment by absolutejam** [comment]
Okay, HTTP is serving just fine when I overwrite the .key and .crt file, but HTTPS isn't. If I wget 127.0.0.1:443 from inside the container, I just get 'ERROR 400: Bad Request', but `netstat -antu` shows that the container is listening on port 443.

Is this because I don't have a .info file?

**Comment by absolutejam** [comment]
Nevermind, user error! Looks like my reverse proxying was bad. I had an issue originally with the certs which I resolved and then the second issue was unrelated.

**Comment by absolutejam** [comment]
Just for information, my docker-compose.yml overwrites the /etc/nginx/ssl folder with one stored on the host machine.

```
version: '2'

services:
  web2py:
    image: thehipbot/web2py
    expose:
      - 8000
      - 443
      - 80
    volumes:
      - "./ssl:/etc/nginx/ssl:ro"
    network_mode: "bridge"
```

and I have an nginx container also on the same network that is linked to this container and proxies requests across.
